command: ["uv", "run", "start-app"]

env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: API_PROXY
    value: "http://localhost:8000/invocations"
  - name: CHAT_APP_PORT
    value: "3000"
  - name: CHAT_PROXY_TIMEOUT_SECONDS
    value: "300"
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: "experiment"
  - name: LLM_ENDPOINT
    value: "databricks-claude-sonnet-4-5"
  - name: VECTOR_SEARCH_INDEX
    value: "shidong_catalog.corp_affairs.docs_index"
  - name: PROMPT_NAME
    value: "shidong_catalog.corp_affairs.rag_prompt"
  - name: PROMPT_ALIAS
    value: "production"
